[[redirects]]
  from = "/api/matches"
  to = "https://api.football-data.org/v4/competitions/CL/matches"
  status = 200
  force = true
  changeOrigin = true
  headers = { X-Auth-Token = "11476ea25dc240e3896d3c993c233c5f" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/netlify/functions/sendEmail"
  to = "https://game-savior-backend.onrender.com/.netlify/functions/sendEmail"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

  [[redirects]]
  from = "/netlify/functions/sendEmail"
  to = "/.netlify/functions/sendEmail"
  status = 200


[build]
  functions = "netlify/functions"
